
title: UnderJS Podcast
email: talk@underjs.ru
description: >- # this means to ignore newlines until "baseurl:"
  UnderJS podcast – самый безызвестный подкаст во всём фронтенде. Underground уже тут.
baseurl: ""
url: "https://underjs.ru"
logo: https://underjs.ru/assets/images/logo-512px.jpg
lang: ru-RU
language: ru
twitter_username: underjs
github_username:  underjs

defaults:
  path: "/assets/images"
  values:
    image: true

author:
  name: "Дмитрий Пацура, Артём Кобзарь"
  twitter: ovrweb

image:
  path: https://underjs.ru/assets/images/logo-512px.jpg
  height: 512
  width: 512

# Misc
license: CC-BY-CA

twitter:
  username: underjs
  creator: ovrweb
  card: summary

# Podcast
podcast:
  title: UnderJS Podcast
  author: Дмитрий Пацура, Артём Кобзарь
  link: https://underjs.ru/
  art: https://underjs.ru/assets/images/logo-1400px.jpg
  subtitle: "UnderJS podcast – самый безызвестный подкаст во всём фронтенде. Underground уже тут."
  summary: >
    UnderJS podcast – самый безызвестный подкаст во всём фронтенде. Underground уже тут.
  itunes:
    category: Technology
  google:
    category: Technology

sc_player:
  auto_play: false
  buying: true
  liking: true
  download: true
  sharing: true
  show_artwork: true
  show_comments: true
  show_playcount: true
  show_user: true
  start_track: 0

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  guests:
    output: true
